# Vagrant multi-machine sample setup
Vagrant.configure("2") do |config|
  config.vm.define "puppetmaster" do |puppetmaster|
    puppetmaster.vm.box = "bento/centos-7.2"
    puppetmaster.vm.network "private_network", ip: "192.168.100.10"
    puppetmaster.vm.hostname = "puppetmaster.puppet.com"
    puppetmaster.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
          end
    puppetmaster.vm.provision "shell", inline: <<-SHELL
	/vagrant/puppet-master.sh
    SHELL
  end

  config.vm.define "puppetagent1" do |puppetagent1|
    puppetagent1.vm.box = "bento/centos-7.2"
    puppetagent1.vm.network "private_network", ip: "192.168.100.11"
    puppetagent1.vm.hostname = "puppetagent1.puppet.com"
    puppetagent1.vm.provision "shell", inline: <<-SHELL
	/vagrant/puppet-agent1.sh
    SHELL
  end

    config.vm.define "puppetagent2" do |puppetagent2|
      puppetagent2.vm.box = "bento/centos-7.2"
      puppetagent2.vm.network "private_network", ip: "192.168.100.12"
      puppetagent2.vm.hostname = "puppetagent2.puppet.com"
      puppetagent2.vm.provision "shell", inline: <<-SHELL
	/vagrant/puppet-agent1.sh
      SHELL
  end

end
