---
- hosts: scheduler_nodes
  remote_user: root
  tasks:

  - name: "Run Puppet on a loop, make sure it's clean"
    command: puppet-run -e production
    register: clean
    until: clean.rc == 0
    retries: 5
    delay: 10
    ignore_errors: yes

- hosts: scheduler_nodes
  remote_user: root
  tasks:

  - name: "Run Puppet on a loop, make sure it's clean"
    command: puppet-run -e production
    register: clean
    until: clean.rc == 0
    retries: 5
    delay: 10
    ignore_errors: yes
